# Objetivo 1
Analizamos la diferencia entre la mioglobina del Homo Sapiens y la del cachalote (Physeter macrocephalus)

## 1.1)

### 1) ¿El alineamiento abarca la secuencia completa de las 2 proteínas? ¿Le parece que es un alineamiento local o global?  
El alineamiento abarca toda la secuencia ya que el Query Cover es del 100%, pero el alineamiento sigue siendo local ya que el algoritmo de blast tiene heurísticas de comparación extendiendo alineamientos locales.
### 2) ¿Se observan gaps en el dot-plot? ¿Cuántos? ¿Cómo se identifican?  
No se observan gaps en el dot-plot  
### 3) Analice el resultado del alineamiento en general tomando en cuenta los valores obtenidos de “Score”, “E value”, “Identities”, “Positives” y “Gaps”.  
Score: 273  
E value: 8x10$^{-101}$   
Identities: 130/154(84%)  
Positives: 143/154(92%)  
Gaps: 0/154(0%)  
- Los resultados muestran un Score alto y un E-value estadísticamente nulo, lo que junto a una identidad del 84% y la ausencia de gaps confirma una altísima conservación evolutiva entre la mioglobina humana y la del cachalote.
### 4) Pruebe cómo varían los resultados del alineamiento anterior modificando los siguientes parámetros: a) Utilizando la Matriz Blosum-80, b) Utilizando un costo de Gap existence y Gap extension: 11:2, c) Utilizando un costo de Gap existence y Gap extension: 9:1. ¿Qué cambios se observan para cada caso?
a) Al utilizar la matriz Blosum-80, como es una matriz optimizada para secuencias de identidad del 80% y nuestra coincidencia es del 84%, se aumentan los valores de recompensa a matches por lo que el score aumentó a 285.

b) Como no observamos gaps, no se encuentran diferencias entre los resultados. Si las secuencias tuvieran gaps, encarecer los costos de apertura y extensión volvería el algoritmo más estricto. Penalizando más fuertemente la ruptura de la secuencia, lo que podría resultar en alineamientos más cortos, con menor cantidad de gaps en el resultado final y un score más bajo. 

c)Al igual que antes, no se encuentran diferencias entre los resultados. Si las secuencias tuvieran gaps, abaratar el costo de apertura y dejar la extensión igual volvería el algoritmo más permisivo, ya que puede permitirse más fácilmente el coste de abrir un gap para no terminar la secuencia prematuramente. Esto podría resultar en alineamientos más largos, con mayor cantidad de gaps y un score más alto.

## 1.2)

### a) Al observar los resultados notarán que hay muchos resultados repetidos o inútiles (la Mb aparece muchas veces y muchas proteínas aparecen cada vez que fueron cristalizadas) ¿Cómo mejoraría la búsqueda para obtener realmente solo aquellas homólogas a la Mb una sola vez?  
Usaría una base de datos que contenga sólo las secuencias de referencia  (RefSeq)
### b) Describa brevemente cada una de las proteínas homólogas encontradas. Compare los E-values, los scores y los alineamientos obtenidos   
![Proteínas homólogas](Img/BlastSearch.png)  
- La mioglobina 1 es la mioglobina que use como query, por eso da 100% de identidad.
- La mioglobina 2 es una sección de la mioglobina 1 pero más corta, por eso tiene 100% de identidad y un E Value muy bajo, pero 64% de Query Cover
- La citoglobina y su isoforma es una proteína que protege las células contra el estrés oxidativo. Logra cubrir casi toda la proteína (95%) pero la identidad es de 28.67%. Aunque la identidad sea baja, el E Value confirma que es homóloga. La única diferencia que veo con la citoglobina es la longitud, por lo que suponemos que es un splicing alternativo.
- Una subunidad de la hemoglobina. Tiene una cobertura e identidad parecida a la citoglobina, pero con un E Value ligeramente mayor, por lo que es apenas un poco más probable de ser una coincidencia.  

### c)¿Cuál es la globina humana más parecida a la Mioglobina? ¿Le sorprende alguno de los resultados?  
La citoglobina es la globina más parecida, ya que tiene la mayor identidad, score, Query cover y un E Value lo suficientemente bajo. Sorprende que bajo estos parámetros solo aparezca significativamente la subunidad zeta y no otras globinas.

### d) ¿Usted cree que encontró todas las proteínas de la familia de las globinas que existen en el genoma humano?  
No, ya que al usar BLOSUM62 puede encontrar secuencias con mucha similitud, pero pueden existir globinas con suficiente divergencia de la mioglobina para no aparecer como match.

### e) Intente encontrar la mayor cantidad de globinas existentes en el genoma humano modificando los parámetros de búsqueda de BLASTp (matriz, costo de gaps, word size, etc.). Indique qué parámetros modificó y qué nuevas proteínas encontró significativamente parecidas a la mioglobina.
![Proteínas homólogas](Img/BlastSearch2.png)
Al usar como matriz BLOSUM45 y modificar el threshold del E Value a 0.1, aumenta la sensibilidad del algoritmo, permitiendo identificar homólogos con baja identidad de secuencia que de otro modo quedarían excluidos. Pudimos encontrar otras subunidades de la hemoglobina homólogas a la mioglobina que antes no aparecían.  
Intentamos encontrar más resultados modificando el word size y los gap costs, pero observamos que estos cambios no arrojaron nuevos resultados significativos ni lograron identificar homólogos más distantes.

### f) Una manera de buscar secuencias homólogas más distantes en la escala evolutiva usando PSI-BLAST. Vuelva a la página de parámetros de la búsqueda, y usando la secuencia de Mb como query realice una nueva búsqueda, pero usando como algoritmo PSI-BLAST. Analice los resultados obtenidos. ¿Encontraron alguna proteína que no había aparecido antes ? ¿Cuántas iteraciones realizaron?
![Proteínas homólogas](Img/BlastSearch3.png)
A la segunda iteración vemos que los E Values de las secuencias que ya estaban bajaron drásticamente y encontramos por primera vez la neuroglobina que como tiene 17% de identidad no aparecía en la búsqueda normal de BLAST, pero gracias a la PSSM aparece con un E Value de 4x10$^{-13}$, por lo que podemos asegurar que es homóloga a la mioglobina.
En las próximas iteraciones no se encontraron nuevos resultados.

# Objetivo 2

## 2.1)

### Repita la misma búsqueda con el parámetro -outfmt 6 y visualice las columnas. Investigue en este link como incluir el alineamiento en las columnas. Repita lo mismo para las otras 2 proteínas. ¿Qué puede concluir del análisis?
![Blast drrA](Img/BlastdrrA.png)
- $\textbf{drrA:}$ El BLAST encontro matches identicos de 100% y 99% de identidad con 0.0 de E Value.  
Esto era de esperarse, al buscar un gen de resistencia bacteriana en una base de datos de bacterias.

![Blast ndk](Img/Blastndk.png)
- $\textbf{ndk:}$ Obtuvimos múltiples coincidencias con una identidad alrededor del 50%, pero con valores de E Values extremadamente bajos del orden de $10^{-40}$. Esto sugiere que, aunque exista una divergencia considerable en la secuencia, la similitud observada sigue siendo altamente significativa desde el punto de vista estadístico.

![Blast map2k7](Img/Blastmap2k7.png)
- $\textbf{map2k7:}$  El análisis mostró alineamientos con identidades relativamente bajas, aunque acompañados por E-values suficientemente significativos como para superar el umbral estadístico de BLAST. Sin embargo, dado que MAP2K7 es una quinasa eucariota y la base contiene principalmente factores de virulencia, es probable que estas coincidencias sean similitudes parciales de regiones altamente conservadas en la evolución debido a su restricción funcional

## 2.2)

### Para analizar el resultado, complete el script (o código de python) a partir del que mostramos más abajo, para generar una tabla que muestre las siguientes columnas: query, hit, cobertura de la query, cobertura del hit, identidad y de qué especie es la proteína hit (donde “busqueda.blast” debe ser el resultado de la búsqueda anterior)

In [9]:
import Bio.SearchIO as bpio
import pandas as pd

resultadosList = list(bpio.parse('Archivos/busqueda.blast', 'blast-xml'))
datosBlast = []

for queryResult in resultadosList:
    queryLen = queryResult.seq_len
    
    for hit in queryResult.hits:
        hitLen = hit.seq_len
        
        especieNombre = "Desconocida"
        if '[' in hit.description and ']' in hit.description:
            especieNombre = hit.description.split('[')[-1].split(']')[0]
            
        # Nos quedamos con el mejor alineamiento de cada hit
        if len(hit.hsps) > 0:
            hspActual = hit.hsps[0]
            
            covQuery = (hspActual.query_span / queryLen) * 100
            covHit = (hspActual.hit_span / hitLen) * 100
            identidadPorcentaje = (hspActual.ident_num / hspActual.aln_span) * 100
            
            datosBlast.append({
                "Query": queryResult.id,
                "Hit": hit.id,
                "Cov_Query(%)": round(covQuery, 2),
                "Cov_Hit(%)": round(covHit, 2),
                "Identidad(%)": round(identidadPorcentaje, 2),
                "Especie": especieNombre
            })

dfResultados = pd.DataFrame(datosBlast)
dfFiltrado = dfResultados[(dfResultados['Cov_Hit(%)'] >= 70.0)]
dfOrdenado = dfFiltrado.sort_values(by='Identidad(%)', ascending=False).reset_index(drop=True)

dfOrdenado

,Query,Hit,Cov_Query(%),Cov_Hit(%),Identidad(%),Especie
0,lcl|NC_002745.2_prot_WP_001015549.1_119,VFG044262(gb|WP_001015549),100.00,100.00,100.00,Staphylococcus aureus subsp. aureus str. Newman
1,lcl|NC_002745.2_prot_WP_000565304.1_147,VFG004450(gb|WP_000565304),100.00,100.00,100.00,Staphylococcus aureus subsp. aureus N315
2,lcl|NC_002745.2_prot_WP_000916704.1_2389,VFG001274(gb|WP_000916704),100.00,100.00,100.00,Staphylococcus aureus subsp. aureus MW2
3,lcl|NC_002745.2_prot_WP_000175722.1_292,VFG049720(gb|WP_000175722),100.00,100.00,100.00,Staphylococcus aureus subsp. aureus USA300_FPR...
4,lcl|NC_002745.2_prot_WP_000160859.1_1041,VFG001318(gb|WP_000160859),100.00,100.00,100.00,Staphylococcus aureus subsp. aureus str. Newman
...,...,...,...,...,...,...
14215,lcl|NC_002745.2_prot_WP_000776422.1_1469,VFG050793(gb|WP_001112093.1),81.74,73.07,17.23,Acinetobacter baumannii D1279779
14216,lcl|NC_002745.2_prot_WP_001220199.1_1044,VFG016173(gb|WP_011168764),73.29,70.59,17.11,Pseudomonas syringae pv. phaseolicola 1448A
14217,lcl|NC_002745.2_prot_WP_001047069.1_885,VFG044083(gb|NP_250948),99.31,94.23,16.67,Pseudomonas aeruginosa PAO1
14218,lcl|NC_002745.2_prot_WP_000477526.1_219,VFG041575(gb|WP_012847751),81.35,96.26,16.27,Edwardsiella tarda EIB202
14219,lcl|NC_002745.2_prot_WP_000773921.1_2499,VFG013728(gb|WP_011273788),85.78,77.22,16.26,Corynebacterium jeikeium K411

# 2.3)

### a) Realice un blast del proteoma de N315 contra la base de enterotoxinas y desarrolle un script que levantando esa información indique cuáles son las enterotoxinas que posee (o sea están presentes en) el proteoma. (Posiblemente obtenga varios hits para cada proteína)

In [19]:
import Bio.SearchIO as bpio
from Bio import BiopythonParserWarning
import pandas as pd
import warnings
warnings.simplefilter('ignore', BiopythonParserWarning)

resultadosList = list(bpio.parse('Archivos/enterotoxinas.blast', 'blast-xml'))
datosBlast = []

for queryResult in resultadosList:
    queryLen = queryResult.seq_len
    for hit in queryResult.hits:
        hitLen = hit.seq_len
        
        if len(hit.hsps) > 0:
            hspActual = hit.hsps[0]
            
            covQuery = (hspActual.query_span / queryLen) * 100
            covHit = (hspActual.hit_span / hitLen) * 100
            identidadPorcentaje = (hspActual.ident_num / hspActual.aln_span) * 100
            
            datosBlast.append({
                "Proteina_N315_Query": queryResult.id,
                "Enterotoxina_Hit": hit.id,
                "Descripción_Hit": hit.description, 
                "Cov_Query(%)": round(covQuery, 2),
                "Cov_Hit(%)": round(covHit, 2),
                "Identidad(%)": round(identidadPorcentaje, 2)
            })

dfEnterotoxinas = pd.DataFrame(datosBlast)

dfFiltrado = dfEnterotoxinas[dfEnterotoxinas['Identidad(%)'] >= 30.0].sort_values(by='Identidad(%)', ascending=False).reset_index(drop=True)
toxinasPresentes = dfFiltrado['Enterotoxina_Hit'].unique()

print(f"Se encontraron matches contra {len(toxinasPresentes)} secuencias representativas de enterotoxinas.")
print("Las enterotoxinas presentes son:")
for toxina in toxinasPresentes:
    print(f"- {toxina}")

dfFiltrado

Se encontraron matches contra 41 secuencias representativas de enterotoxinas.
Las enterotoxinas presentes son:
- seg
- sec3
- sei
- sen
- sep
- seo
- selw
- sel
- tsst-1
- Gr10/sel33
- sec2
- selx
- sec1
- selu
- sem
- selv
- Gr1/sel26
- see
- sea
- sek
- seb
- Gr5/sel29p
- Gr9/sel32
- Gr4/sel28
- seq
- selj
- Gr6/sel30
- ser
- sed
- Gr8/sel31
- ses
- Gr3/sel27
- Gr12/ses-3p
- seh
- Gr2/selz
- Gr7/ses-2p
- Gr11/seh-2p
- sely
- gnl|BL_ORD_ID|10
- set
- gnl|BL_ORD_ID|11

,Proteina_N315_Query,Enterotoxina_Hit,Descripción_Hit,Cov_Query(%),Cov_Hit(%),Identidad(%)
0,lcl|NC_002745.2_prot_WP_000736712.1_1758,seg,AAC26660.1,100.00,99.61,100.00
1,lcl|NC_002745.2_prot_WP_000278088.1_1957,sec3,CAA35972.1,100.00,99.63,100.00
2,lcl|NC_002745.2_prot_WP_000713847.1_1761,sei,AAC26661.1,100.00,99.59,100.00
3,lcl|NC_002745.2_prot_WP_001236362.1_1759,sen,AAG36956.1,100.00,96.91,100.00
4,lcl|NC_002745.2_prot_WP_000034846.1_1893,sep,BAB43036.1,100.00,99.62,99.62
...,...,...,...,...,...,...
309,lcl|NC_002745.2_prot_WP_000713847.1_1761,sec1,CAA29260.1,65.29,59.93,30.11
310,lcl|NC_002745.2_prot_WP_000746599.1_1956,Gr10/sel33,NZ_FGMI01000018.1,86.67,83.60,30.09
311,lcl|NC_002745.2_prot_WP_000034846.1_1893,sec2,AAR20496.1,99.62,98.50,30.04
312,lcl|NC_002745.2_prot_WP_000821658.1_1762,sec3,CAA35972.1,78.24,72.66,30.00
313,lcl|NC_002745.2_prot_SA_RS15170_1760,gnl|BL_ORD_ID|11,Gr11/seh-2p - fully repaired NC_017351.1,40.47,50.00,30.00

### b) Programe algún criterio de decisión en función de la identidad/cobertura. En caso de que más de un hit cumpla las expectativas, indique que encontró más de una proteína

In [20]:
# 2. Definimos nuestro Criterio de Decisión:
umbralIdentidad = 80.0
umbralCobertura = 80.0

dfEstricto = dfEnterotoxinas[
    (dfEnterotoxinas['Identidad(%)'] >= umbralIdentidad) &
    (dfEnterotoxinas['Cov_Hit(%)'] >= umbralCobertura)
]

resultadosFinales = []
gruposQuery = dfEstricto.groupby('Proteina_N315_Query')

for queryId, dfGrupo in gruposQuery:
    dfGrupoOrdenado = dfGrupo.sort_values(by='Identidad(%)', ascending=False)
    if len(dfGrupoOrdenado) == 1:
        mejorHit = dfGrupoOrdenado.iloc[0]['Enterotoxina_Hit']
        resultadosFinales.append({
            "Proteina_N315": queryId,
            "Enterotoxina_Asignada": mejorHit,
            "Criterio_Decision": "Hit unico válido"
        })
    else:
        # Si mas de un hit cumple las expectativas
        nombresToxinas = " | ".join(dfGrupoOrdenado['Enterotoxina_Hit'].tolist())
        resultadosFinales.append({
            "Proteina_N315": queryId,
            "Enterotoxina_Asignada": nombresToxinas,
            "Criterio_Decision": "Se encontró más de una proteína"
        })

dfDecision = pd.DataFrame(resultadosFinales)
dfDecision

,Proteina_N315,Enterotoxina_Asignada,Criterio_Decision
0,lcl|NC_002745.2_prot_WP_000034846.1_1893,sep,Hit unico válido
1,lcl|NC_002745.2_prot_WP_000278088.1_1957,sec3 | sec2 | sec1,Se encontró más de una proteína
2,lcl|NC_002745.2_prot_WP_000475325.1_371,selx,Hit unico válido
3,lcl|NC_002745.2_prot_WP_000713847.1_1761,sei,Hit unico válido
4,lcl|NC_002745.2_prot_WP_000736712.1_1758,seg,Hit unico válido
5,lcl|NC_002745.2_prot_WP_000746599.1_1956,sel,Hit unico válido
6,lcl|NC_002745.2_prot_WP_000821658.1_1762,sem | selv,Se encontró más de una proteína
7,lcl|NC_002745.2_prot_WP_001035599.1_1959,tsst-1,Hit unico válido
8,lcl|NC_002745.2_prot_WP_001236362.1_1759,sen,Hit unico válido
9,lcl|NC_002745.2_prot_WP_010922839.1_1763,seo,Hit unico válido

Dado el alto grado de homología dentro de la familia de las enterotoxinas, se observó que una única secuencia query alineaba con múltiples variantes. Para decidir, se programó un filtro estableciendo un umbral de $\ge$ 80% de Identidad y $\ge$ 80% de Cobertura.  
En aquellos casos donde múltiples toxinas superaron el umbral para una misma query, el algoritmo lo clasificó indicando que se encontró más de una proteína válida.